name: nuevo_trabajo_devcontainer

version: '3.8'

services:
  php-apache:
    build: ./php-apache
    ports:
      - "8090:80"
    volumes:
      - ..:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: basquet_bd
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8091:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data: